import { useEffect, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { AlertCircle, CheckCircle2 } from "lucide-react";
import { api } from "../lib/api";
import Field from "../components/Field";

export function AuthShell({ children }) { return <main className="auth-page"><div className="auth-decoration"><div className="brand-lockup"><span className="brand-mark">B</span><div><b>BandRoom</b><small>REHEARSAL SPACE</small></div></div><div className="auth-hero"><span className="eyebrow">MUSIC · SPACE · COMMUNITY</span><h2>让每一次排练，<em>准时开始。</em></h2><p>多房间预约、会员权益与排练设备，集中管理你的乐队时光。</p><div className="soundwave"><i /><i /><i /><i /><i /><i /><i /><i /><i /></div></div></div><section className="auth-panel"><div className="panel-top"><span className="live-dot" /> REHEARSAL ROOM ACCESS</div>{children}<p className="copyright">BandRoom · 乐队排练室管理系统</p></section></main>; }
function Notice({ children, error = false }) { return <div className={`notice ${error ? "error" : "success"}`}><span>{error ? <AlertCircle size={16} /> : <CheckCircle2 size={16} />}</span>{children}</div>; }
export function VerifyEmail() { const [message, setMessage] = useState("正在验证邮箱…"); const [error, setError] = useState(""); useEffect(() => { const token = new URLSearchParams(window.location.search).get("token"); if (!token) return setError("验证链接缺少 token"); api(`/api/auth/verify?token=${encodeURIComponent(token)}`).then((d) => setMessage(d.message)).catch((e) => { setError(e.message); setMessage(""); }); }, []); return <AuthShell><Notice error={!!error}>{error || message}</Notice><Link className="button primary full" to="/login">返回登录</Link></AuthShell>; }
export default function AuthPage({ mode = "login", onLogin }) { const navigate = useNavigate(); const view = mode; const [form, setForm] = useState({ name: "", email: "", phone: "", password: "", token: new URLSearchParams(window.location.search).get("token") || "" }); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false); function changeView(next) { setForm({ name: "", email: "", phone: "", password: "" }); setError(""); setMessage(""); navigate(next === "login" ? "/login" : `/${next === "forgot" ? "forgot-password" : next}`); } async function submit(event) { event.preventDefault(); setBusy(true); setError(""); try { if (view === "login") { const data = await api("/api/auth/login", { method: "POST", body: JSON.stringify({ email: form.email, password: form.password }) }); onLogin(data.user); navigate(data.user.role === "owner" ? "/owner" : "/customer/bookings"); } else if (view === "register") { const data = await api("/api/auth/register", { method: "POST", body: JSON.stringify(form) }); changeView("login"); setMessage(data.message); } else if (view === "forgot") { const data = await api("/api/auth/password-reset/request", { method: "POST", body: JSON.stringify({ email: form.email }) }); setMessage(data.message); } else { const data = await api("/api/auth/password-reset/confirm", { method: "POST", body: JSON.stringify({ token: form.token, password: form.password }) }); changeView("login"); setMessage(data.message); } } catch (e) { setError(e.message); } finally { setBusy(false); } } const titles = { login: "登录 BandRoom", register: "创建顾客账号", forgot: "找回密码", reset: "设置新密码" }; return <AuthShell><div className="auth-kicker">ACCOUNT</div><h1>{titles[view]}</h1><p className="auth-subtitle">{view === "register" ? "注册后即可查看空闲房间并提交预约。" : "登录后管理你的排练预约与会员权益。"}</p>{message && <Notice>{message}</Notice>}{error && <Notice error>{error}</Notice>}<form onSubmit={submit} className="auth-form">{view === "register" && <><Field label="联系人姓名" name="name" value={form.name} onChange={setForm} required /><Field label="手机号" name="phone" value={form.phone} onChange={setForm} required /></>}{view === "reset" && <Field label="重置令牌" name="token" value={form.token || ""} onChange={setForm} required />}{view !== "reset" && <Field label="邮箱" name="email" type="email" value={form.email} onChange={setForm} required />}{view !== "forgot" && <Field label={view === "reset" ? "新密码" : "密码"} name="password" type="password" value={form.password} onChange={setForm} required />}<button className="button primary full" disabled={busy}>{busy ? "处理中…" : view === "login" ? "登录" : view === "register" ? "注册并验证邮箱" : view === "forgot" ? "发送重置邮件" : "确认新密码"}</button></form><div className="auth-links">{view === "login" ? <><button onClick={() => changeView("register")}>立即注册</button><button onClick={() => changeView("forgot")}>忘记密码</button></> : <button onClick={() => changeView("login")}>返回登录</button>}</div></AuthShell>; }
