import { useEffect, useState } from "react";
import { useNavigate, useLocation, Outlet, Link } from "react-router-dom";
import { Bell, CalendarDays, ChevronRight, DoorOpen, LayoutDashboard, LogOut, Menu, Package, Settings, ShieldCheck, UsersRound, Clock3 } from "lucide-react";
import { useFeedback } from "./lib/useFeedback";
import { Notice } from "./components/ui";
import { api } from "./lib/api";

const customerNav = [{ to: "/customer/home", label: "场馆首页", icon: DoorOpen }, { to: "/customer/bookings", label: "预约排练", icon: CalendarDays }, { to: "/customer/history", label: "我的预约", icon: Clock3 }, { to: "/customer/membership", label: "会员卡", icon: ShieldCheck }, { to: "/customer/notifications", label: "通知", icon: Bell }];
const ownerNav = [{ to: "/owner", label: "数据概览", icon: LayoutDashboard }, { to: "/owner/bookings", label: "预约管理", icon: CalendarDays }, { to: "/owner/rooms", label: "排练房", icon: DoorOpen }, { to: "/owner/equipment", label: "设备管理", icon: Package }, { to: "/owner/membership", label: "会员卡", icon: UsersRound }, { to: "/owner/settings", label: "场馆设置", icon: Settings }];

function SideNav({ items, onNavigate }) { const location = useLocation(); return <nav id="main-navigation" className="side-nav">{items.map(({ to, label, icon: Icon }) => <Link key={to} onClick={onNavigate} aria-current={location.pathname === to ? "page" : undefined} className={location.pathname === to ? "active" : ""} to={to}><Icon size={18} /><span>{label}</span><ChevronRight className="nav-arrow" size={15} /></Link>)}</nav>; }
export function ProtectedLayout({ user, onLogout }) { const navigate = useNavigate(); const location = useLocation(); const [menuOpen, setMenuOpen] = useState(false); useEffect(() => { setMenuOpen(false); }, [location.pathname]); useEffect(() => { if (!menuOpen) return; const close = (event) => { if (event.key === "Escape") setMenuOpen(false); }; window.addEventListener("keydown", close); return () => window.removeEventListener("keydown", close); }, [menuOpen]); const { notice, busy, run } = useFeedback(); async function logout() { await run(async () => { await api("/api/auth/logout", { method: "POST" }); onLogout(); navigate("/login"); }); } const items = user.role === "owner" ? ownerNav : customerNav; return <div className={`app-shell ${menuOpen ? "menu-open" : ""}`} >{menuOpen && <button className="nav-backdrop" aria-label="关闭导航" onClick={() => setMenuOpen(false)} />}<aside className="sidebar"><Link className="side-brand" to={user.role === "owner" ? "/owner" : "/customer/home"}><span className="brand-mark">B</span><span><b>BandRoom</b><small>音乐排练空间</small></span></Link><SideNav items={items} onNavigate={() => setMenuOpen(false)} /><div className="side-user"><div className="user-avatar">{user.name?.slice(0, 1)}</div><div><b>{user.name}</b><small>{user.role === "owner" ? "场馆老板" : "顾客会员"}</small></div><button disabled={busy} title="退出登录" onClick={logout}><LogOut size={17} /></button></div></aside><main className="content"><div className="mobile-topbar"><span className="brand-mark">B</span><b>{user.role === "owner" ? "老板后台" : "顾客端"}</b><button aria-label={menuOpen ? "收起导航" : "打开导航"} aria-expanded={menuOpen} aria-controls="main-navigation" onClick={() => setMenuOpen((open) => !open)}><Menu /></button></div>{notice && <Notice type={notice.type}>{notice.text}</Notice>}<Outlet context={{ user }} /></main></div>; }
export function CustomerLayout() { return <Outlet />; }
export function OwnerLayout() { return <Outlet />; }
